import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "@/app/globals.css";
import { cn } from "@/lib/utils";
import AdminNavBar from "@/components/Administrateur/AdminNavBar";
import AdminSideNavbar from "@/components/Administrateur/AdminSideNavbar";
import SideNavbar from "../SideNavbar";
import Nav from "./Nav";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app"
};

export default function UserLayout({
  children
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body
        className={cn(
          "min-h-screen w-full bg-white text-black flex ",
          inter.className,
          {
            "debug-screens": process.env.NODE_ENV === "development"
          }
        )}
      >
        {/* sidebar */}
        <div style={{ marginTop: "3rem" }}> {/* Ajoute une marge en haut */}
          <SideNavbar />
        </div>
        <Nav/>
        {/* main page */}
        <div className="p-8 w-full">{children}</div>
      </body>
    </html>
  );
}
