import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "@/app/globals.css";

import SideNavbar from "@/components/SideNavbar";
import { cn } from "@/lib/utils";
import NavBar from "@/components/user/navbar";
import AdminNavBar from "@/components/Administrateur/AdminNavBar";
import AdminSideNavbar from "@/components/Administrateur/AdminSideNavbar";
import SideNavbarEnseignant from "@/components/Enseignant/SideNavbarEnseignant";
import NavBarEnseignant from "@/components/Enseignant/NavBarEnseignant";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app"
};

export default function EnseignantLayout({
  children
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body
        className={cn(
          "min-h-screen w-full bg-white text-black flex ",
          inter.className,
          {
            "debug-screens": process.env.NODE_ENV === "development"
          }
        )}
      >
        {/* sidebar */}
        <div style={{ marginTop: "3rem" }}> {/* Ajoute une marge en haut */}
          <SideNavbarEnseignant />
        </div>
        <NavBarEnseignant/>
        {/* main page */}
        <div className="p-8 w-full">{children}</div>
      </body>
    </html>
  );
}
