import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "@/app/globals.css";

import { cn } from "@/lib/utils";
import EtudiantNavBar from "@/components/Etudiant/EtudiantNavBar";
import SideNavbarEtudiant from "@/components/Etudiant/SideNavbarEtudiant";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app"
};

export default function EtudiantLayout({
  children
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body
        className={cn(
          "min-h-screen w-full bg-white text-black flex ",
          inter.className,
          {
            "debug-screens": process.env.NODE_ENV === "development"
          }
        )}
      >
        {/* sidebar */}
        <div style={{ marginTop: "3rem" }}> {/* Ajoute une marge en haut */}
          <SideNavbarEtudiant />
        </div>
        <EtudiantNavBar/>
        {/* main page */}
        <div className="p-8 w-full">{children}</div>
      </body>
    </html>
  );
}
